CurriculumDavid/Controllers/ComLingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CurriculumDavid.Data;
using CurriculumDavid.Models;
using Microsoft.AspNetCore.Authorization;

namespace CurriculumDavid.Controllers
{
    [Authorize(Roles = "Administrador, GestorDados, Utilizador")]
    public class ComLingController : Controller
    {
        private readonly CurriculumBdContext bd;

        public ComLingController(CurriculumBdContext context)
        {
            bd = context;
        }

        // GET: ComLing
        public async Task<IActionResult> Index(string nomePesquisar, int pagina = 1)
        {
            Paginacao paginacao = new Paginacao
            {
                TotalItems = await bd.ComLing.Where(p => nomePesquisar == null || p.Lingua.Contains(nomePesquisar)).CountAsync(),
                PaginaAtual = pagina
            };

            List<ComLing> comLing = await bd.ComLing.Where(p => nomePesquisar == null || p.Lingua.Contains(nomePesquisar))
                .Include(p=> p.DadosPessoais)
                .OrderBy(p => p.Lingua)
                .Skip(paginacao.ItemsPorPagina * (pagina - 1))
                .Take(paginacao.ItemsPorPagina)
                .ToListAsync();

            ListaDadosViewModel modelo = new ListaDadosViewModel
            {
                Paginacao = paginacao,
                ComLing = comLing,
                NomePesquisar = nomePesquisar
            };

            return base.View(modelo);
        }
      

        // GET: ComLing/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comLing = await bd.ComLing
                .FirstOrDefaultAsync(m => m.CompetenciasId == id);
            if (comLing == null)
            {
                return NotFound();
            }

            return View(comLing);
        }

        // GET: ComLing/Create
        public IActionResult Create()
        {
            ViewData["DadosPessoaisId"] = new SelectList(bd.DadosPessoais, "DadosPessoaisId", "Email");
            return View();
        }

        // POST: ComLing/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CompetenciasId,Lingua,CompreensaoOral,Leitura,ProducaoOral,InteracaoOral,Escrita,DadosPessoaisId")] ComLing comLing)
        {
            if (ModelState.IsValid)
            {
                bd.Add(comLing);
                await bd.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["DadosPessoaisId"] = new SelectList(bd.DadosPessoais, "DadosPessoaisId", "Email", comLing.DadosPessoaisId);
            return View(comLing);
        }

        // GET: ComLing/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comLing = await bd.ComLing.FindAsync(id);
            if (comLing == null)
            {
                return NotFound();
            }
            ViewData["DadosPessoaisId"] = new SelectList(bd.DadosPessoais, "DadosPessoaisId", "Email", comLing.DadosPessoaisId);
            return View(comLing);
        }

        // POST: ComLing/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CompetenciasId,Lingua,CompreensaoOral,Leitura,ProducaoOral,InteracaoOral,Escrita,DadosPessoaisId")] ComLing comLing)
        {
            if (id != comLing.CompetenciasId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    bd.Update(comLing);
                    await bd.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ComLingExists(comLing.CompetenciasId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DadosPessoaisId"] = new SelectList(bd.DadosPessoais, "DadosPessoaisId", "Email", comLing.DadosPessoaisId);
            return View(comLing);
        }

        // GET: ComLing/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comLing = await bd.ComLing
                .FirstOrDefaultAsync(m => m.CompetenciasId == id);
            if (comLing == null)
            {
                return NotFound();
            }

            return View(comLing);
        }

        // POST: ComLing/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var comLing = await bd.ComLing.FindAsync(id);
            bd.ComLing.Remove(comLing);
            await bd.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ComLingExists(int id)
        {
            return bd.ComLing.Any(e => e.CompetenciasId == id);
        }
    }
}

CurriculumDavid/Controllers/EduForController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CurriculumDavid.Data;
using CurriculumDavid.Models;
using Microsoft.AspNetCore.Authorization;

namespace CurriculumDavid.Controllers
{
    [Authorize(Roles = "Administrador, GestorDados, Utilizador")]
    public class EduForController : Controller
    {
        private readonly CurriculumBdContext bd;

        public EduForController(CurriculumBdContext context)
        {
            bd = context;
        }

        // GET: EduFor
        public async Task<IActionResult> Index(string nomePesquisar, int pagina = 1)
        {
            Paginacao paginacao = new Paginacao
            {
                TotalItems = await bd.EduFor.Where(p => nomePesquisar == null || p.NomeFormacao.Contains(nomePesquisar)).CountAsync(),
                PaginaAtual = pagina
            };

            List<EduFor> eduFors = await bd.EduFor.Where(p => nomePesquisar == null || p.NomeFormacao.Contains(nomePesquisar))
                .Include(p => p.DadosPessoais)
                .OrderByDescending(p =>p.DataFim)
                .Skip(paginacao.ItemsPorPagina * (pagina - 1))
                .Take(paginacao.ItemsPorPagina)
                .ToListAsync();

            ListaDadosViewModel modelo = new ListaDadosViewModel
            {
                Paginacao = paginacao,
                EduFor = eduFors,
                NomePesquisar = nomePesquisar
            };

            return base.View(modelo);
        }
        // GET: EduFor/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eduFor = await bd.EduFor
                .Include(e => e.DadosPessoais)
                .FirstOrDefaultAsync(m => m.EduForId == id);
            if (eduFor == null)
            {
                return NotFound();
            }

            return View(eduFor);
        }

        // GET: EduFor/Create
        public IActionResult Create()
        {
            ViewData["DadosPessoaisId"] = new SelectList(bd.DadosPessoais, "DadosPessoaisId", "Email");
            return View();
        }

        // POST: EduFor/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EduForId,DataInicio,DataFim,NomeFormacao,EntFormadora,DadosPessoaisId")] EduFor eduFor)
        {
            if (ModelState.IsValid)
            {
                bd.Add(eduFor);
                await bd.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["DadosPessoaisId"] = new SelectList(bd.DadosPessoais, "DadosPessoaisId", "Email", eduFor.DadosPessoaisId);
            return View(eduFor);
        }

        // GET: EduFor/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eduFor = await bd.EduFor.FindAsync(id);
            if (eduFor == null)
            {
                return NotFound();
            }
            ViewData["DadosPessoaisId"] = new SelectList(bd.DadosPessoais, "DadosPessoaisId", "Email", eduFor.DadosPessoaisId);
            return View(eduFor);
        }

        // POST: EduFor/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EduForId,DataInicio,DataFim,NomeFormacao,EntFormadora,DadosPessoaisId")] EduFor eduFor)
        {
            if (id != eduFor.EduForId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    bd.Update(eduFor);
                    await bd.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EduForExists(eduFor.EduForId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DadosPessoaisId"] = new SelectList(bd.DadosPessoais, "DadosPessoaisId", "Email", eduFor.DadosPessoaisId);
            return View(eduFor);
        }

        // GET: EduFor/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eduFor = await bd.EduFor
		.Include(e => e.DadosPessoais)
                .FirstOrDefaultAsync(m => m.EduForId == id);
            if (eduFor == null)
            {
                return NotFound();
            }

            return View(eduFor);
        }

        // POST: EduFor/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var eduFor = await bd.EduFor.FindAsync(id);
            bd.EduFor.Remove(eduFor);
            await bd.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EduForExists(int id)
        {
            return bd.EduFor.Any(e => e.EduForId == id);
        }
    }
}

CurriculumDavid/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CurriculumDavid</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CurriculumDavid</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - CurriculumDavid - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

CurriculumDavid/Views/Shared/_Layout_home.cshtml
<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewData["Title"] - CurriculumDavid</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">


    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body id="uo">
    <header>
        <div>
            <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-3">
                <div class="container-fluid">
                    @*<a id="inicio" href="#" class="navbar-brand mr-3">A página do David</a>
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                        <span class="navbar-toggler-icon"></span>
                    </button>*@
                    <div class="collapse navbar-collapse" id="navbarCollapse">
                        <div class="navbar-nav">
                            @if(User.Identity.IsAuthenticated){
                            <a asp-action="Index" asp-controller="Home" class="nav-item nav-link fa fa-home" title="Início"></a>
                            <a asp-action="Index" asp-controller="DadosPessoais" class="nav-item nav-link" target="_self">Dados Pessoais</a>
                            <a asp-action="Index" asp-controller="ExpProfissional" class="nav-item nav-link" target="_self">Experiência Profissional</a>
                            <a asp-action="Index" asp-controller="EduFor" class="nav-item nav-link" target="_self">Educação e Formação</a>
                            <a asp-action="Index" asp-controller="ComLing" class="nav-item nav-link" target="_self">Competências Linguistícas</a>
                            }

                        </div>
                        <div class="navbar-nav ml-auto">
                            <partial name="_LoginPartial" />
                          
                        </div>
                    </div>
                        </div>
                    </div>
                </div>
            </nav>
        </div>
    </header>
    <div class="container">
        <main>
            @RenderBody()

        </main>
    </div>
    <br />
    <br />
    <br />
    <footer>
        <div class="row bg-dark">
            <div class="col-md-6">
                <a class="btn btn-primary" asp-action="Index" asp-controller="Home">Voltar ao início</a>

                <a href="#inicio" class="btn btn-primary">Ir para o topo</a>
                <!--<a href="../index.html">Voltar ao início</a>-->
            </div>
            <div class="col-md-6 text-white text-md-right">
                <p>
                    Copyright &copy; 2021
                </p>
                @*<a href="https://www.linkedin.com/in/david-petrucci-pinto-b20a4014" target="_blank">
            <img src="../Img/linkedin_logo_1.jpg" title="Linkedin" alt="Linkedin">
        </a> <br />*@
                <!--<a href="#" class="text-dark">Terms of Use</a>
    <span class="text-muted mx-2">|</span>
    <a href="#" class="text-dark">Privacy Policy</a>-->
                @*<a href="http://www.ipg.pt/website/" target="_blank"><img src="../Img/logotipo_ipg.jpg" title="Site IPG" alt="Logo IPG"></a>
        <a href="https://upskill.pt/" target="_blank"><img src="../Img/Upskills.png" title="UPskil" alt="Logo Upskill"></a>*@

            </div>
        </div>
       
    </footer>


    @*<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>*@
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)

</body>
</html>